openapi: 3.1.0
info:
  title: Nifli.com REST API
  description:
    $ref: ./info-description.md
  license:
    name: 'Commercial Enterprise'
    url: 'https://autheus.com'
  version: 1.0.0
tags: 
  - $ref: tenants/tags/Accounts.yaml
  - $ref: oidc/tags/ClientApplications.yaml
servers:
  - url: 'https://api.test.nifli.com'
    description: Integration and Test/Staging server
  - url: 'https://api.nifli.com'
    description: Production server (Not Deployed)
paths:
  /accounts:
    $ref: tenants/paths/accounts.yaml
  '/accounts/{accountId}':
    $ref: tenants/paths/accounts_{accountId}.yaml
  /clients:
    $ref: oidc/paths/clients.yaml
  '/clients/{clientId}':
    $ref: oidc/paths/clients_{clientId}.yaml
security:
  - OAuth2: []
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: >-
        Authorization header using the Bearer scheme. Example: Authorization:
        Bearer {token}
      flows:
        clientCredentials:
          tokenUrl: /token
          scopes:
            confidential_client: A customer's server-side programmatic client of the Autheus APIs 
    ApiKey:
      type: apiKey
      description: >-
        Authorization header using the API key scheme. Example: Authorization:
        apikey {apikey}
      name: Authorization
      in: header
